// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-HKbJE1ZG_61P-LaThu5OE3CMZ1tDXuQ',
    appId: '1:909098231141:web:3118cd4c34b99f15362d8c',
    messagingSenderId: '909098231141',
    projectId: 'trainbookinguts',
    authDomain: 'trainbookinguts.firebaseapp.com',
    storageBucket: 'trainbookinguts.appspot.com',
    measurementId: 'G-PTG37XB0WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB43-em-GrYukieRgKeKdjwdHuazs8V4MY',
    appId: '1:909098231141:android:19e5d9a701ee766d362d8c',
    messagingSenderId: '909098231141',
    projectId: 'trainbookinguts',
    storageBucket: 'trainbookinguts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-v5TH7Fb438W14v680JQyVE9lwRrSlrk',
    appId: '1:909098231141:ios:918d191890fa9f45362d8c',
    messagingSenderId: '909098231141',
    projectId: 'trainbookinguts',
    storageBucket: 'trainbookinguts.appspot.com',
    iosBundleId: 'com.example.trainbookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-v5TH7Fb438W14v680JQyVE9lwRrSlrk',
    appId: '1:909098231141:ios:918d191890fa9f45362d8c',
    messagingSenderId: '909098231141',
    projectId: 'trainbookinguts',
    storageBucket: 'trainbookinguts.appspot.com',
    iosBundleId: 'com.example.trainbookingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-HKbJE1ZG_61P-LaThu5OE3CMZ1tDXuQ',
    appId: '1:909098231141:web:96f612af2a8bec57362d8c',
    messagingSenderId: '909098231141',
    projectId: 'trainbookinguts',
    authDomain: 'trainbookinguts.firebaseapp.com',
    storageBucket: 'trainbookinguts.appspot.com',
    measurementId: 'G-9Y67BZ5ZLB',
  );

}